export { evaluate, parseParam } from './algorithms/shared';
export { bisection } from './algorithms/bisection';
export { fixedPoint } from './algorithms/fixedPoint';
export { aitken } from './algorithms/aitken';
export { newtonRaphson } from './algorithms/newtonRaphson';
export { secant } from './algorithms/secant';
export { regulaFalsi } from './algorithms/regulaFalsi';
export { lagrange } from './algorithms/lagrange';
export { trapezoidal } from './algorithms/trapezoidal';
export { simpson13 } from './algorithms/simpson13';
export { simpson38 } from './algorithms/simpson38';
export { midpoint } from './algorithms/midpoint';
export { solveODE } from './algorithms/solveODE';
export { monteCarlo } from './algorithms/monteCarlo';
export { recommendG } from './algorithms/recommendG';
